### ISSUE TITLE
Curious about the difference between WPT and actual Chrome

### ISSUE THREAD

**Issue by GuillaumeRossolini** [pmeenan/http2priorities#1]
Hi Patrick,

I uploaded the test page on our server to try it out:
https://www.instantluxe.com/http2priorities/index.html

And sure enough, WPT seems to agree that prioritization by Chrome/nginx is ok:
https://www.webpagetest.org/result/181123_QN_9d0d915a020d113d158b19ee8ad9d75d/

However, the waterfall from Chrome on my desktop (Windows 10, v72.0.3619.0 (Build officiel) canary (64 bits)) doesn't show the same at all:
https://drive.google.com/file/d/1VRtK4P_1MTHBDXw-j2-6Zs6k6Vo97Tio/view?usp=sharing

v70.0.3538.110 (Build officiel) (64 bits) shows the same as the canary build.

Would you happen to know if this is an issue in the browser?

**Comment by pmeenan** [comment]
I'll add a note to the docs but I don't recommend ever using Chrome's built-in connection profiles for this kind of thing. The "shaping" is done inside of Chrome and not on the network so it basically introduces it's own buffering.  There are good options for all platforms here: https://calendar.perfplanet.com/2016/testing-with-realistic-networking-conditions/

The waterfall in dev tools also leaves a lot to be desired and doesn't show the raw chunk timings, just the start and end times.

**Comment by GuillaumeRossolini** [comment]
Ok, thank you for the details.
