### ISSUE TITLE
Test doesn't seem to display

### ISSUE THREAD

**Issue by li-brich** [pmeenan/http2priorities#2]
I'm interested in testing our infrastructure's support for HTTP/2 priority using the standalone test page. However, it doesn't appear to work anymore. If I download the HTML file and open it locally, it just displays a white screen and Chrome's console doesn't show any errors. I get the same result using the copy hosted at the URL in the readme.

I'm using Chrome 107.0.5304.87 (Official Build) (arm64). I'm not sure if this has been used much since it was written but I was wondering if this is a known issue and if there are any workarounds.

**Comment by pmeenan** [comment]
Seems to be working ok:

[https://www.webpagetest.org/http2priorities.html?image=https%3A%2F%2Fcdn.cnn.com%2Fcnnnext%2Fdam%2Fassets%2F200626135726-062520-trump-congress-financial-records-photoillo-large-tease.jpg](https://www.webpagetest.org/http2priorities.html?image=https%3A%2F%2Fcdn.cnn.com%2Fcnnnext%2Fdam%2Fassets%2F200626135726-062520-trump-congress-financial-records-photoillo-large-tease.jpg) loads the test page with the referenced image.

Are you passing it an image URL to test and url-encoding the image URL?

**Comment by li-brich** [comment]
Ah, my mistake. I was jumping right into http2priorities.html having barely skimmed through the readme. From the screenshot near the top, I was expecting a UI with a place to configure the test – enter a URL, set the number of test runs, maybe change priority, etc. Out of curiosity, what is that a screenshot of?

**Comment by pmeenan** [comment]
The screenshot is of webpagetest.org (the old UI) where you usually want to
trigger the test from once you have an appropriate image on your origin.

The priorities are adjusted by the test page to see how well the server
deals with interrupting in-flight streams for high-priority requests.

**Comment by li-brich** [comment]
Excellent. Thank you for the explanation, not to mention your work creating this tool in the first place.
